- name: LEMP Compile Nginx + PHP-FPM From Source + Mariadb + Wordpress
  hosts: all
  become: yes
  become_method: sudo
  
  roles:
    - Dependencies
    - Nginx
    - Vhost
    - PHP-FPM
    - Mariadb
    - Wordpress
    #- Filebeat
    #- Remove
    - Addon-services
    - SSL-Snap

  tasks:
    - name: reboot all server
      reboot:
        reboot_timeout: 3600

